import type { ToolProfile } from "../../utils/config.js";

export const DYNAMIC_MANAGEMENT_TOOL_NAMES = [
  "discover_tools",
  "select_toolset",
  "get_active_toolset",
  "reset_toolset",
] as const;

export const DYNAMIC_MANAGEMENT_TOOL_NAME_SET: ReadonlySet<string> = new Set(
  DYNAMIC_MANAGEMENT_TOOL_NAMES,
);

export const CORE_EXISTING_TOOL_NAMES = [
  "get_td_info",
  "search_operators",
  "get_td_classes",
  "get_operator_workflow_guide",
  "find_td_nodes",
  "get_td_node_parameters",
  "get_td_node_flags",
  "get_td_topology",
  "get_td_node_errors",
  "summarize_td_errors",
  "get_preview",
  "validate_operator_chain",
  "list_recipes",
] as const;

export const PROTECTED_CORE_TOOL_NAMES = [
  "get_td_info",
  ...DYNAMIC_MANAGEMENT_TOOL_NAMES,
  ...CORE_EXISTING_TOOL_NAMES.slice(1),
] as const;

/** Every existing tool whose MCP annotation declares `destructiveHint: true`. */
export const SAFE_PROFILE_EXCLUDE: ReadonlySet<string> = new Set([
  "execute_python_script",
  "exec_node_method",
  "create_python_script",
  "author_script_operator",
  "delete_td_node",
  "rebuild_network",
  "edit_dat_content",
  "set_dat_content",
  "edit_shader_live_loop",
  "create_panic",
  "manage_checkpoint",
  "manage_component",
  "manage_packages",
  "make_portable_tox",
  "export_recipe_bundle",
  "optimize_performance",
  "publish_recipe_bundle",
  "import_recipe_bundle",
  "scaffold_recipe_template",
  "attach_docs_as_assets",
  "local_marketplace_index",
  "marketplace_index_seed",
  "refresh_asset_previews",
  "install_library_package",
  "create_modulators",
  "project_documentation_site",
  "import_recipe_from_url",
  "export_palette_component",
  "collect_project_assets",
  "bundle_dependencies",
  "export_externalized_tree",
  "repair_network",
  "swap_operator",
  "export_sop_to_svg",
  "generative_classics_pack",
  "create_safety_blackout_chain",
  "merge_vaults",
  "manage_component_storage",
  "macro_recorder",
]);

export const DIRECTORY_PROFILE_TOOL_NAMES = [
  "get_td_info",
  "search_operators",
  "get_td_classes",
  "get_operator_workflow_guide",
  "find_td_nodes",
  "get_td_node_parameters",
  "get_td_node_flags",
  "get_td_topology",
  "create_td_node",
  "connect_nodes",
  "update_td_node_parameters",
  "validate_operator_chain",
  "list_recipes",
  "apply_recipe",
  "browse_library",
] as const;

export const RAW_CODE_TOOL_NAMES = [
  "execute_python_script",
  "exec_node_method",
  "create_python_script",
  "author_script_operator",
] as const;

export const INSPECT_EXTRA_TOOL_NAMES = [
  "analyze_project",
  "check_operator_availability",
  "compact_graph_digest",
  "compare_operator_docs",
  "compare_td_nodes",
  "diagnose_hardware_environment",
  "diff_snapshots",
  "document_network",
  "get_bridge_logs",
  "get_dat_content",
  "get_inline_preview",
  "get_module_help",
  "get_node_state_runtime",
  "get_parameter_menu",
  "get_td_class_details",
  "get_td_nodes",
  "get_td_performance",
  "get_technique_detail",
  "get_tutorial",
  "inspect_gpu_and_displays",
  "inspect_op_extensions_storage",
  "lint_recipe_library",
  "profile_cook_cost",
  "read_parameter_modes",
  "search_touchdesigner_knowledge",
  "snapshot_td_graph",
  "watch_node",
] as const;

export const BUILD_EXTRA_TOOL_NAMES = [
  "add_custom_parameters",
  "animate_parameter",
  "apply_glsl_top_mapping",
  "apply_lut",
  "apply_post_processing",
  "arrange_network",
  "auto_ui_from_params",
  "batch_operations",
  "bind_audio_reactive",
  "bind_to_channel",
  "build_chop_chain",
  "build_pop_chain",
  "build_sop_geometry",
  "connect_nodes",
  "create_3d_audio_reactive",
  "create_3d_scene",
  "create_audio_glsl_uniforms",
  "create_audio_reactive",
  "create_automation_lane",
  "create_color_grade",
  "create_color_wheels",
  "create_container",
  "create_control_panel",
  "create_control_surface",
  "create_datamosh",
  "create_displacement_warp",
  "create_dither",
  "create_feedback_network",
  "create_feedback_tunnel",
  "create_glsl_material",
  "create_glsl_shader",
  "create_gpu_particle_field",
  "create_halftone",
  "create_histogram_scope",
  "create_kaleidoscope",
  "create_keyframe_animation",
  "create_kinetic_text",
  "create_layer_mixer",
  "create_layer_stack",
  "create_media_bin",
  "create_multi_output",
  "create_node_chain",
  "create_npr_filter",
  "create_optical_flow",
  "create_palette",
  "create_particle_system",
  "create_pbr_scene",
  "create_pixel_sort",
  "create_point_cloud",
  "create_pop_particle_system",
  "create_preset_morph",
  "create_projection_mapping",
  "create_reaction_diffusion",
  "create_spectrum",
  "create_td_node",
  "create_tempo_sync",
  "create_test_pattern",
  "create_text_3d",
  "create_text_overlay",
  "create_video_player",
  "create_video_scopes",
  "create_visual_system",
  "create_waveform",
  "detect_onsets",
  "detect_pitch",
  "detect_tempo",
  "disconnect_nodes",
  "duplicate_network",
  "extract_audio_features",
  "extract_palette",
  "image_to_particles",
  "set_parameter_expression",
  "set_parameters_batch",
  "setup_output",
  "update_td_node_parameters",
] as const;

export const SHOW_EXTRA_TOOL_NAMES = [
  "add_timecode_overlay",
  "atem_switcher_control",
  "compose_cue_list",
  "connect_ableton_link_session",
  "connect_blackmagic_atem",
  "connect_companion_surface",
  "connect_obs_recorder",
  "connect_qlab_cue_stack",
  "connect_resolume_arena",
  "connect_spout_syphon_router",
  "control_timeline_transport",
  "create_autopilot",
  "create_companion_surface",
  "create_cue_sequencer",
  "create_decklink_io_router",
  "create_direct_display_output",
  "create_dome_output",
  "create_histogram_scope",
  "create_ltc_timecode_bridge",
  "create_monitor_layout_panel",
  "create_multi_output",
  "create_ndi_router_matrix",
  "create_scene_timeline",
  "create_scheduler",
  "create_set_navigator",
  "create_setlist_runner",
  "create_show_failover",
  "create_stage_dashboard",
  "create_test_pattern",
  "create_transition",
  "create_video_scopes",
  "create_window_output_matrix",
  "diagnose_hardware_environment",
  "get_td_performance",
  "inspect_gpu_and_displays",
  "manage_cue",
  "obs_stream_control",
  "profile_cook_cost",
  "qlab_osc_bridge",
  "resolume_vdmx_output_chain",
  "set_perform_mode",
  "setup_output",
  "show_preflight_report",
  "sync_external_clock",
  "sync_timecode",
  "watch_node",
  "watch_parameter_changes",
] as const;

export const LIBRARY_EXTRA_TOOL_NAMES = [
  "browse_library",
  "browse_vault_library",
  "checksum_and_verify_pack",
  "compare_operator_docs",
  "component_changelog_trail",
  "component_link_health",
  "diff_library_assets",
  "draft_recipe_from_operator_chain",
  "draft_recipe_from_technique",
  "draft_recipe_from_tutorial",
  "get_dat_content",
  "get_technique_detail",
  "get_tutorial",
  "inspect_component_manifest",
  "library_lineage_graph",
  "lint_recipe_library",
  "load_session_profile",
  "narrate_set",
  "plan_td_version_migration",
  "provenance_stamp",
  "recall_similar_work",
  "search_touchdesigner_knowledge",
  "validate_library_asset",
] as const;

function sortedUnion(...lists: readonly (readonly string[])[]): readonly string[] {
  return [...new Set(lists.flat())].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
}

export const CORE_PROFILE_TOOL_NAMES = sortedUnion(CORE_EXISTING_TOOL_NAMES);
export const INSPECT_PROFILE_TOOL_NAMES = sortedUnion(
  CORE_EXISTING_TOOL_NAMES,
  INSPECT_EXTRA_TOOL_NAMES,
);
export const BUILD_PROFILE_TOOL_NAMES = sortedUnion(
  CORE_EXISTING_TOOL_NAMES,
  BUILD_EXTRA_TOOL_NAMES,
);
export const SHOW_PROFILE_TOOL_NAMES = sortedUnion(CORE_EXISTING_TOOL_NAMES, SHOW_EXTRA_TOOL_NAMES);
export const LIBRARY_PROFILE_TOOL_NAMES = sortedUnion(
  CORE_EXISTING_TOOL_NAMES,
  LIBRARY_EXTRA_TOOL_NAMES,
);

const STATIC_PROFILE_TOOL_NAMES: Record<
  Exclude<ToolProfile, "full" | "safe">,
  readonly string[]
> = {
  directory: DIRECTORY_PROFILE_TOOL_NAMES,
  core: CORE_PROFILE_TOOL_NAMES,
  inspect: INSPECT_PROFILE_TOOL_NAMES,
  build: BUILD_PROFILE_TOOL_NAMES,
  show: SHOW_PROFILE_TOOL_NAMES,
  library: LIBRARY_PROFILE_TOOL_NAMES,
};

export function staticProfileAllows(name: string, profile: ToolProfile): boolean {
  if (profile === "full") return true;
  if (profile === "safe") return !SAFE_PROFILE_EXCLUDE.has(name);
  return STATIC_PROFILE_TOOL_NAMES[profile].includes(name);
}
