import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import type { Tool } from "@modelcontextprotocol/sdk/types.js";
import { createTdmcpServer } from "../src/server/tdmcpServer.js";
import { fingerprintTool } from "../src/tools/toolsets/metadata.js";
import type { GeneratedToolMetadataEntry } from "../src/tools/toolsets/types.js";
import { loadConfig } from "../src/utils/config.js";
import { silentLogger } from "../src/utils/logger.js";

type GeneratorMode = "--write" | "--check" | "--write-baseline";

const GENERATED_METADATA_PATH = fileURLToPath(
  new URL("../src/tools/toolsets/toolMetadata.generated.ts", import.meta.url),
);
const BASELINE_PATH = fileURLToPath(
  new URL("../tests/fixtures/tool-contract-baseline.json", import.meta.url),
);
const LEGACY_TOOL_COUNT = 497;

function explicitGeneratorEnv(overrides: NodeJS.ProcessEnv): NodeJS.ProcessEnv {
  return {
    TDMCP_TOOL_PROFILE: "full",
    TDMCP_DYNAMIC_TOOLSETS: "off",
    TDMCP_RAW_PYTHON: "on",
    TDMCP_EVENTS: "off",
    TDMCP_LOG_LEVEL: "silent",
    TDMCP_RAG_ENABLED: "0",
    TDMCP_PROJECT_RAG_ENABLED: "0",
    TDMCP_RAG_APPLY_CARD: overrides.TDMCP_RAG_APPLY_CARD ?? "off",
  };
}

async function collectFullTools(overrides: NodeJS.ProcessEnv): Promise<Tool[]> {
  const env = explicitGeneratorEnv(overrides);
  const config = loadConfig(env);
  const server = createTdmcpServer(config, { logger: silentLogger });
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  const client = new Client({ name: "tdmcp-metadata-generator", version: "0.0.0" });
  try {
    await Promise.all([server.connect(serverTransport), client.connect(clientTransport)]);
    return (await client.listTools()).tools.sort((a, b) =>
      a.name < b.name ? -1 : a.name > b.name ? 1 : 0,
    );
  } finally {
    await Promise.allSettled([client.close(), server.close()]);
  }
}

function metadataEntries(tools: readonly Tool[]): Record<string, GeneratedToolMetadataEntry> {
  return Object.fromEntries(
    tools.map((tool) => [
      tool.name,
      {
        bytes: Buffer.byteLength(JSON.stringify(tool), "utf8"),
        fingerprint: fingerprintTool(tool),
      },
    ]),
  );
}

function renderMetadataModule(tools: readonly Tool[]): string {
  const entries = Object.entries(metadataEntries(tools))
    .map(([name, entry]) => {
      if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)) {
        throw new Error(`Tool name cannot be rendered as a TypeScript identifier: ${name}`);
      }
      return `  ${name}: {
    bytes: ${entry.bytes},
    fingerprint: "${entry.fingerprint}",
  },`;
    })
    .join("\n");
  return `/**
 * Generated by scripts/gen-tool-metadata.ts.
 * Regenerate with \`npm run tools:metadata:gen\`; verify with \`npm run tools:metadata:check\`.
 */

import type { GeneratedToolMetadataEntry } from "./types.js";

export const TOOL_METADATA: Record<string, GeneratedToolMetadataEntry> = {
${entries}
};
`;
}

function renderBaseline(tools: readonly Tool[]): string {
  if (tools.length !== LEGACY_TOOL_COUNT) {
    throw new Error(
      `Refusing to write legacy baseline: expected ${LEGACY_TOOL_COUNT} tools, received ${tools.length}.`,
    );
  }
  return `${JSON.stringify(
    {
      count: LEGACY_TOOL_COUNT,
      fingerprints: Object.fromEntries(tools.map((tool) => [tool.name, fingerprintTool(tool)])),
    },
    null,
    2,
  )}\n`;
}

function parseMode(args: readonly string[]): GeneratorMode | undefined {
  if (args.length !== 1) return undefined;
  const [mode] = args;
  if (mode === "--write" || mode === "--check" || mode === "--write-baseline") {
    return mode;
  }
  return undefined;
}

async function run(args: readonly string[]): Promise<number> {
  const mode = parseMode(args);
  if (!mode) {
    console.error("Usage: tsx scripts/gen-tool-metadata.ts (--write|--check|--write-baseline)");
    return 2;
  }

  if (mode === "--write-baseline" && existsSync(BASELINE_PATH)) {
    console.error(`Refusing to replace existing legacy baseline: ${BASELINE_PATH}`);
    return 1;
  }

  try {
    const tools = await collectFullTools({});
    if (mode === "--write") {
      writeFileSync(GENERATED_METADATA_PATH, renderMetadataModule(tools), "utf8");
      console.log(`generated metadata entries: ${tools.length}`);
      return 0;
    }
    if (mode === "--write-baseline") {
      writeFileSync(BASELINE_PATH, renderBaseline(tools), { encoding: "utf8", flag: "wx" });
      console.log(`legacy baseline entries: ${tools.length}`);
      return 0;
    }

    const expected = renderMetadataModule(tools);
    const current = existsSync(GENERATED_METADATA_PATH)
      ? readFileSync(GENERATED_METADATA_PATH, "utf8")
      : undefined;
    if (current !== expected) {
      console.error("Tool metadata is stale. Run `npm run tools:metadata:gen`.");
      return 1;
    }
    console.log("tool metadata is current");
    return 0;
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    return 1;
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  run(process.argv.slice(2)).then((exitCode) => {
    process.exitCode = exitCode;
  });
}
